M48
; DRILL file KiCad 10.0.1 date 2026-06-08T18:18:19
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-08T18:18:19+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C6.000
%
G90
G05
T1
X18.0Y-76.5
X18.0Y-141.5
X135.0Y-76.5
X135.0Y-141.5
T2
X99.72Y-80.75
X99.72Y-99.25
X99.72Y-117.75
X99.72Y-136.25
M30
